### ISSUE TITLE
Not possible to mock image requests in @codeceptjs/mock-request

### ISSUE THREAD

**Issue by olgabenchuk** [codecept-js/mock-request#8]
#### What are you trying to achieve?

Be able to mock different kind of HTTP requests using `@codeceptjs/mock-request`

#### What do you get instead?

[Only `fetch` and `xhr` request types can be mocked by default](https://github.com/codeceptjs/mock-request/blob/master/connector/Puppeteer.js#L30) using `@codeceptjs/mock-request` and there is no way to extend it via the `codecept.conf.js`

```js
{
    MockRequestHelper: {
      require: '@codeceptjs/mock-request',
      mode: 'record',
    },
}
```

#### Possible Solution

Provide a way to override the settings via the config

```js
{
    MockRequestHelper: {
      require: '@codeceptjs/mock-request',
      mode: 'record',
      adapterOptions: {
        puppeteer: { 
          requestResourceTypes: ['xhr', 'fetch', 'image'], // handle other types of requests
        },
      },
    },
}
```

Currently, it's not possible because it expects an instance of a page `page: this.Puppeteer.page`

**Comment by kobenguyent** [comment]
You may try the mock request built in by Puppeteer helper -> https://codecept.io/puppeteer/#mocking-network-requests
